In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
indep=dataset[['User ID', 'Age', 'EstimatedSalary','Gender_Male']]
dep=dataset[['Purchased']]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [10]:
from sklearn.model_selection import GridSearchCV

param_grid={'criterion':['gini','entropy'],
            'max_features':['auto','sqrt','log2'],
            'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')

#fiting the model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\ELCOT\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [12]:
#print the best parameter aftertunning
#print (grid.best_params_)
re=grid.cv_results_
grid_prediction=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

#print classification Report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_prediction)

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_prediction,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.925937287340759

In [16]:
print("The confusion matrix:\n",cm)
print("The report:\n",clf_report)

The confusion matrix:
 [[78  7]
 [ 3 46]]
The report:
               precision    recall  f1-score   support

           0       0.96      0.92      0.94        85
           1       0.87      0.94      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.93      0.92       134
weighted avg       0.93      0.93      0.93       134

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9631452581032413

In [20]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.087274,0.019338,0.012139,0.011517,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.843811,0.828959,0.832483,0.906166,0.922185,0.866721,0.039384,11
1,0.390817,0.046559,0.039334,0.007840,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.885356,0.870047,0.870362,0.867097,0.961755,0.890923,0.035984,6
2,0.069429,0.015094,0.007690,0.003929,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.804764,0.886792,0.832483,0.829124,0.922185,0.855070,0.042953,12
3,0.369274,0.024605,0.050326,0.006498,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.885356,0.850809,0.870362,0.906166,0.943041,0.891147,0.031658,4
4,0.060901,0.006429,0.006479,0.004500,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.867478,0.868752,0.869709,0.867097,0.923510,0.879309,0.022120,9
5,0.373831,0.033600,0.045039,0.008420,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.887346,0.870047,0.870362,0.906166,0.943041,0.895393,0.027277,2
6,0.066882,0.004886,0.010917,0.003750,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.867478,0.868752,0.852044,0.886792,0.901744,0.875362,0.017183,10
7,0.383137,0.024295,0.040167,0.008753,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.867478,0.850809,0.870362,0.925272,0.962264,0.895237,0.041852,3
8,0.063314,0.004134,0.008094,0.007140,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.864871,0.850809,0.870362,0.906166,0.943041,0.887050,0.033419,7
9,0.430619,0.057483,0.042543,0.009923,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.885356,0.831253,0.870362,0.925272,0.943041,0.891057,0.039775,5
10,0.051896,0.008109,0.006084,0.004245,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.847141,0.888107,0.870362,0.867097,0.961755,0.886892,0.039626,8
11,0.385633,0.052489,0.038127,0.012144,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.885356,0.870047,0.870362,0.925272,0.943041,0.898816,0.029914,1

In [ ]:
table=pd.DataFrame.from_dict(re)
table

In [23]:
age_input=int(input("enter age:"))
salary_input=float(input("enter salary:"))
sex_male_input=int(input("enter sex male 0 or 1:"))
id_input=int(input("enter_id"))

enter age:33
enter salary:30000
enter sex male 0 or 1:0
enter_id45678

In [25]:
Future_prediction=grid.predict([[age_input,salary_input,sex_male_input,id_input]])
print("Future_prediction={}".format(Future_prediction))

Future_prediction=[1]

In [26]:
Future_prediction

array([1], dtype=int64)